version: '3.8'

services:
  backend-service:
    container_name: backend-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: ep-morning-voice-a12ydsc4-pooler.ap-southeast-1.aws.neon.tech
      DATABASE_PORT: 5432
      DATABASE_USERNAME: neondb_owner
      DATABASE_PASSWORD: npg_pJ39SmHTNgiU
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - default

volumes:
  redis-data:

networks:
  default: