version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
